//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassFun
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment1
    {
        public int AppointmentID { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<int> Duration { get; set; }
        public string Client { get; set; }
        public string Counselor { get; set; }
        public string ScheduledBy { get; set; }
        public string RoomName { get; set; }
        public string Notes { get; set; }
        public string Assignment { get; set; }
        public Nullable<bool> Kept { get; set; }
    }
}
