//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassFun
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public Client()
        {
            this.Client1 = new HashSet<Client>();
            this.ScheduledFors = new HashSet<ScheduledFor>();
        }
    
        public int ClientID { get; set; }
        public string FoundOut { get; set; }
        public string ReminderMethod { get; set; }
        public Nullable<int> ReferredByClientID { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual ICollection<Client> Client1 { get; set; }
        public virtual Client Client2 { get; set; }
        public virtual ICollection<ScheduledFor> ScheduledFors { get; set; }
    }
}
