//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassFun
{
    using System;
    using System.Collections.Generic;
    
    public partial class contain
    {
        public string ParentID { get; set; }
        public string childID { get; set; }
        public Nullable<int> Qty { get; set; }
    }
}
