//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassFun
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Appointments = new HashSet<Appointment>();
            this.Employee1 = new HashSet<Employee>();
        }
    
        public int EmployeeID { get; set; }
        public Nullable<System.DateTime> DateHired { get; set; }
        public Nullable<decimal> Wage { get; set; }
        public int SupervisorID { get; set; }
    
        public virtual ICollection<Appointment> Appointments { get; set; }
        public virtual Person Person { get; set; }
        public virtual ICollection<Employee> Employee1 { get; set; }
        public virtual Employee Employee2 { get; set; }
    }
}
