//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassFun
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class jeffersonEntities : DbContext
    {
        public jeffersonEntities()
            : base("name=jeffersonEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Appointment> Appointments { get; set; }
        public DbSet<Client> Clients { get; set; }
        public DbSet<Counselor> Counselors { get; set; }
        public DbSet<Employee> Employees { get; set; }
        public DbSet<Person> People { get; set; }
        public DbSet<Room> Rooms { get; set; }
        public DbSet<ScheduledFor> ScheduledFors { get; set; }
        public DbSet<contain> contains { get; set; }
        public DbSet<part> parts { get; set; }
        public DbSet<Appointment1> Appointments1 { get; set; }
        public DbSet<Client1> Clients1 { get; set; }
        public DbSet<Counselor1> Counselor1 { get; set; }
        public DbSet<Employee1> Employees1 { get; set; }
        public DbSet<Room1> Rooms1 { get; set; }
    }
}
